name: Benchmark

on:
  workflow_run:
    workflows: [Test]
    types: [completed]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --verbose
      - name: Benchmark
        run: make bench
